version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edtech_fastapi_app
    restart: unless-stopped
    command: >
      uvicorn src.infrastructure.api.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-edtech_dev}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-edtech_dev}
    depends_on:
      - db
    networks:
      - edtech_network

  db:
    image: postgres:16
    container_name: edtech_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-edtech_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edtech_network
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edtech_alembic
    entrypoint: ["tail", "-f", "/dev/null"]  # keeps container up but idle
    working_dir: /usr/src/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-edtech_dev}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-edtech_dev}
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - edtech_network

  proxy:
    image: caddy:2.7.5-alpine
    container_name: edtech_caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app
    networks:
      - edtech_network

volumes:
  postgres_data:
  caddy_data:

networks:
  edtech_network:
    driver: bridge
